version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: newsdb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: newsdb
      DB_USERNAME: root
      DB_PASSWORD: secret
      NEWSAPI_KEY: ${NEWSAPI_KEY}
      GUARDIAN_KEY: ${GUARDIAN_KEY}
      NYTIMES_KEY: ${NYTIMES_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  dbdata:
